# Generated by Django 4.1.5 on 2023-01-28 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatedUpdatedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Kit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        help_text="Введите название картины",
                        verbose_name="Название картины",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "author",
                    models.CharField(
                        help_text="Введите автора картины",
                        max_length=100,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "total_crosses",
                    models.PositiveIntegerField(
                        help_text="введите общее число крестиков в картине",
                        verbose_name="размер картины",
                    ),
                ),
                (
                    "design_created_year",
                    models.DateField(
                        blank=True,
                        help_text="Введите год, в котором был разработан дизайн",
                        null=True,
                        verbose_name="Год создания дизайна",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kit_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создала набор на сайте",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "unique_together": {("title", "author")},
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=250, null=True, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "embroiderer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Проект",
                    ),
                ),
                (
                    "kit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project",
                        to="cross.kit",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "createdupdatedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cross.createdupdatedmodel",
                    ),
                ),
                (
                    "crosses_done",
                    models.PositiveIntegerField(
                        help_text="Введите количество вышитых крестиков",
                        verbose_name="Вышито крестиков",
                    ),
                ),
                (
                    "embroiderer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Прогресс",
                    ),
                ),
                (
                    "kit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="cross.kit",
                        verbose_name="Прогресс",
                    ),
                ),
            ],
            options={
                "verbose_name": ("прогресс",),
                "ordering": ["-modified"],
                "unique_together": {("embroiderer", "kit")},
            },
            bases=("cross.createdupdatedmodel",),
        ),
    ]
