# Generated by Django 4.1.5 on 2023-01-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kit",
            name="company",
            field=models.CharField(
                blank=True,
                help_text="Введите название производителя",
                max_length=100,
                null=True,
                verbose_name="Производитель",
            ),
        ),
        migrations.AlterField(
            model_name="kit",
            name="author",
            field=models.CharField(
                blank=True,
                help_text="Введите автора картины",
                max_length=100,
                null=True,
                verbose_name="Автор",
            ),
        ),
    ]
