# Generated by Django 4.1.5 on 2023-02-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kit",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="kit",
            name="length",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
