# Generated by Django 4.1.5 on 2023-02-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0002_alter_kit_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kit",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="kit",
            name="length",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="kit",
            name="size",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="введите общее число крестиков в картине",
                null=True,
                verbose_name="size",
            ),
        ),
    ]
