# Generated by Django 4.1.5 on 2023-01-28 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0002_kit_company_alter_kit_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="kit",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_slug",
                to="cross.kit",
                verbose_name="Слаг проекта",
            ),
        ),
    ]
