# Generated by Django 4.1.5 on 2023-01-28 15:18

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0004_alter_kit_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kit",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True, editable=False, null=True, populate_from="title"
            ),
        ),
    ]
