# Generated by Django 4.1.5 on 2023-01-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0005_alter_kit_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kit",
            name="title",
            field=models.TextField(
                help_text="Введите название картины",
                unique=True,
                verbose_name="Название картины",
            ),
        ),
    ]
