# Generated by Django 4.1.5 on 2023-01-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0006_alter_kit_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="kit",
            name="title_translation",
            field=models.CharField(
                blank=True,
                help_text="Введите перевод названия на английский или нажмите Enter",
                max_length=100,
                null=True,
                verbose_name="Перевод названия",
            ),
        ),
    ]
