# Generated by Django 4.1.5 on 2023-01-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0008_alter_kit_slug_alter_kit_total_crosses"),
    ]

    operations = [
        migrations.AddField(
            model_name="kit",
            name="to_be_slug",
            field=models.CharField(
                blank=True,
                help_text="Вспомогательное поле, оставьте пустым",
                max_length=100,
                null=True,
                verbose_name="Будущий слаг",
            ),
        ),
    ]
