# Generated by Django 4.1.5 on 2023-01-30 11:11

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0009_kit_to_be_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kit",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True, editable=False, null=True, populate_from="to_be_slug"
            ),
        ),
    ]
