# Generated by Django 4.1.5 on 2023-01-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0010_alter_kit_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kit",
            name="to_be_slug",
        ),
        migrations.AlterField(
            model_name="kit",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
