# Generated by Django 4.1.5 on 2023-01-30 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0011_remove_kit_to_be_slug_alter_kit_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="design_slug",
            field=models.ForeignKey(
                default=23,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_slug",
                to="cross.kit",
                verbose_name="Слаг проекта",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
