# Generated by Django 4.1.5 on 2023-01-30 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0012_project_design_slug_alter_project_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="design_slug",
        ),
    ]
