# Generated by Django 4.1.5 on 2023-01-30 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cross", "0012_project_design_slug_alter_project_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Designer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        help_text="Введите имя дизайнера",
                        unique=True,
                        verbose_name="Имя дизайнера",
                    ),
                ),
                (
                    "title_translation",
                    models.CharField(
                        blank=True,
                        help_text="Введите перевод названия на английский или нажмите Enter",
                        max_length=100,
                        null=True,
                        verbose_name="Перевод названия",
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True)),
                (
                    "country",
                    models.TextField(
                        blank=True,
                        help_text="Введите страну производства",
                        null=True,
                        verbose_name="Страна",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="project",
            name="design_slug",
        ),
        migrations.AlterField(
            model_name="project",
            name="embroiderer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Вышивальщица",
            ),
        ),
    ]
