# Generated by Django 4.1.5 on 2023-01-30 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0013_designer_remove_project_design_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        help_text="Введите название компании",
                        unique=True,
                        verbose_name="Название компании",
                    ),
                ),
                (
                    "title_translation",
                    models.CharField(
                        blank=True,
                        help_text="Введите перевод названия на английский или нажмите Enter",
                        max_length=100,
                        null=True,
                        verbose_name="Перевод названия",
                    ),
                ),
                (
                    "country",
                    models.TextField(
                        blank=True,
                        help_text="Введите страну производства",
                        null=True,
                        verbose_name="Страна",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, null=True)),
                (
                    "designer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company",
                        to="cross.designer",
                        verbose_name="Компания",
                    ),
                ),
            ],
        ),
    ]
