# Generated by Django 4.1.5 on 2023-01-30 14:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0013_designer_remove_project_design_slug_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="kit",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="createdupdatedmodel",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="createdupdatedmodel",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="createdupdatedmodel",
            name="title",
            field=models.TextField(
                default="My title",
                help_text="Введите имя",
                unique=True,
                verbose_name="Имя",
            ),
        ),
        migrations.AddField(
            model_name="createdupdatedmodel",
            name="title_translation",
            field=models.CharField(
                blank=True,
                help_text="Введите перевод названия на английский или нажмите Enter",
                max_length=100,
                null=True,
                verbose_name="Перевод",
            ),
        ),
        migrations.AddField(
            model_name="designer",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="kit",
            name="designer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kit",
                to="cross.designer",
                verbose_name="Дизайнер",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="title",
            field=models.TextField(
                default="My title",
                help_text="Введите имя",
                unique=True,
                verbose_name="Имя",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="title_translation",
            field=models.CharField(
                blank=True,
                help_text="Введите перевод названия на английский или нажмите Enter",
                max_length=100,
                null=True,
                verbose_name="Перевод",
            ),
        ),
        migrations.AlterField(
            model_name="designer",
            name="title",
            field=models.TextField(
                default="My title",
                help_text="Введите имя",
                unique=True,
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="designer",
            name="title_translation",
            field=models.CharField(
                blank=True,
                help_text="Введите перевод названия на английский или нажмите Enter",
                max_length=100,
                null=True,
                verbose_name="Перевод",
            ),
        ),
        migrations.AlterField(
            model_name="kit",
            name="title",
            field=models.TextField(
                default="My title",
                help_text="Введите имя",
                unique=True,
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="kit",
            name="title_translation",
            field=models.CharField(
                blank=True,
                help_text="Введите перевод названия на английский или нажмите Enter",
                max_length=100,
                null=True,
                verbose_name="Перевод",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="kit",
            unique_together={("title", "designer")},
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        default="My title",
                        help_text="Введите имя",
                        unique=True,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "title_translation",
                    models.CharField(
                        blank=True,
                        help_text="Введите перевод названия на английский или нажмите Enter",
                        max_length=100,
                        null=True,
                        verbose_name="Перевод",
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True)),
                (
                    "country",
                    models.TextField(
                        blank=True,
                        help_text="Введите страну производства",
                        null=True,
                        verbose_name="Страна",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "designer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="designer",
                        to="cross.designer",
                        verbose_name="Дизайнер",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="kit",
            name="author",
        ),
        migrations.AlterField(
            model_name="kit",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kit",
                to="cross.company",
                verbose_name="Дизайн",
            ),
        ),
    ]
