# Generated by Django 4.1.5 on 2023-01-30 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0014_alter_kit_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kit",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company",
                to="cross.company",
                verbose_name="Компания",
            ),
        ),
    ]
