# Generated by Django 4.1.5 on 2023-02-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0016_alter_progress_embroiderer_alter_progress_kit"),
    ]

    operations = [
        migrations.AddField(
            model_name="designer",
            name="name",
            field=models.CharField(
                default="Введите имя",
                help_text="Введите имя дизайнера",
                max_length=30,
                verbose_name="Имя",
            ),
        ),
    ]
