# Generated by Django 4.1.5 on 2023-02-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0017_designer_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="designer",
            name="name",
        ),
    ]
