# Generated by Django 4.1.5 on 2023-02-10 12:49

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cross", "0019_alter_company_title_alter_createdupdatedmodel_title_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="progress",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="progress",
            name="day",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="progress",
            unique_together={("embroiderer", "kit", "day")},
        ),
    ]
