# Generated by Django 4.1.5 on 2023-02-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cross", "0020_alter_progress_unique_together_progress_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progress",
            name="day",
            field=models.DateField(auto_now=True),
        ),
    ]
